AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - spec/**/*.rb

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SignalException:
  EnforcedStyle: only_raise

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: true

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable
  AutoCorrect: false

Rails/DynamicFindBy:
  Enabled: false

